/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CadastroController;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author brunocesar
 */
public class Cadastro extends javax.swing.JFrame {

    private final CadastroController controller;

    public Cadastro() {
        initComponents();
        controller = new CadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SalvarBarbeirojButton = new javax.swing.JButton();
        VoltarParaLoginjButton = new javax.swing.JButton();
        NomeBarbeirojTextField1 = new javax.swing.JTextField();
        UsernameBarbeirojTextField2 = new javax.swing.JTextField();
        SenhaBarbeirojPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nome de Usuário:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, 20));

        SalvarBarbeirojButton.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        SalvarBarbeirojButton.setText("Salvar");
        SalvarBarbeirojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBarbeirojButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SalvarBarbeirojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 180, -1));

        VoltarParaLoginjButton.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        VoltarParaLoginjButton.setText("Voltar");
        VoltarParaLoginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarParaLoginjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarParaLoginjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 180, -1));
        getContentPane().add(NomeBarbeirojTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 310, 30));

        UsernameBarbeirojTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameBarbeirojTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameBarbeirojTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 310, 30));
        getContentPane().add(SenhaBarbeirojPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 207, 310, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/cadastro.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameBarbeirojTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameBarbeirojTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameBarbeirojTextField2ActionPerformed

    private void SalvarBarbeirojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBarbeirojButtonActionPerformed

        if (Utilitarios.Validacao.isNullOrEmpty(NomeBarbeirojTextField1.getText())
                || Utilitarios.Validacao.isNullOrEmpty(UsernameBarbeirojTextField2.getText())
                || Utilitarios.Validacao.isNullOrEmpty(SenhaBarbeirojPasswordField1.getText())) {

            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");
            return;
        } else {
            controller.salvarNovoBarbeiro();
        }

    }//GEN-LAST:event_SalvarBarbeirojButtonActionPerformed

    private void VoltarParaLoginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarParaLoginjButtonActionPerformed

        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarParaLoginjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeBarbeirojTextField1;
    private javax.swing.JButton SalvarBarbeirojButton;
    private javax.swing.JPasswordField SenhaBarbeirojPasswordField1;
    private javax.swing.JTextField UsernameBarbeirojTextField2;
    private javax.swing.JButton VoltarParaLoginjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public JTextField getNomeBarbeirojTextField1() {
        return NomeBarbeirojTextField1;
    }

    public void setNomeBarbeirojTextField1(JTextField NomeBarbeirojTextField1) {
        this.NomeBarbeirojTextField1 = NomeBarbeirojTextField1;
    }

    public JPasswordField getSenhaBarbeirojPasswordField1() {
        return SenhaBarbeirojPasswordField1;
    }

    public void setSenhaBarbeirojPasswordField1(JPasswordField SenhaBarbeirojPasswordField1) {
        this.SenhaBarbeirojPasswordField1 = SenhaBarbeirojPasswordField1;
    }

    public JTextField getUsernameBarbeirojTextField2() {
        return UsernameBarbeirojTextField2;
    }

    public void setUsernameBarbeirojTextField2(JTextField UsernameBarbeirojTextField2) {
        this.UsernameBarbeirojTextField2 = UsernameBarbeirojTextField2;
    }

}
