/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;
import Model.Barbeiro;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author brunocesar
 */
public class Login extends javax.swing.JFrame {

    private final LoginController loginController;
    public static Barbeiro barbeiroSecao;
    
    public Login() {
        initComponents();
        loginController = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsuariojTextField1 = new javax.swing.JTextField();
        CadastrarjToggleButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SenhajPasswordField1 = new javax.swing.JPasswordField();
        LogarjToggleButton = new javax.swing.JToggleButton();
        LoginjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Barbearia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 245, 245));
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 245, 245));
        jLabel3.setText("Usuário");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        UsuariojTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariojTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(UsuariojTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 270, 40));

        CadastrarjToggleButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        CadastrarjToggleButton.setForeground(new java.awt.Color(1, 1, 1));
        CadastrarjToggleButton.setText("Cadastrar");
        CadastrarjToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarjToggleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarjToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 190, -1));

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Não possui cadastro? Clique em cadastrar.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 290, 340, 30));

        SenhajPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhajPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(SenhajPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 270, 40));

        LogarjToggleButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LogarjToggleButton.setForeground(new java.awt.Color(1, 1, 1));
        LogarjToggleButton.setText("Logar");
        LogarjToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogarjToggleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogarjToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 190, -1));

        LoginjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/barber-shop-mock-up_7939-1652.jpg"))); // NOI18N
        LoginjLabel.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(LoginjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 411));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuariojTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariojTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariojTextField1ActionPerformed

    private void LogarjToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogarjToggleButtonActionPerformed
        loginController.logar();
    }//GEN-LAST:event_LogarjToggleButtonActionPerformed

    private void SenhajPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhajPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhajPasswordField1ActionPerformed

    private void CadastrarjToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarjToggleButtonActionPerformed
        
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CadastrarjToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CadastrarjToggleButton;
    private javax.swing.JToggleButton LogarjToggleButton;
    private javax.swing.JLabel LoginjLabel;
    private javax.swing.JPasswordField SenhajPasswordField1;
    private javax.swing.JTextField UsuariojTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    
    public JTextField getUsuariojTextField1() {
        return UsuariojTextField1;
    }

    public void setUsuariojTextField1(JTextField UsuariojTextField1) {
        this.UsuariojTextField1 = UsuariojTextField1;
    }

    public JPasswordField getSenhajPasswordField1() {
        return SenhajPasswordField1;
    }

    public void setSenhajPasswordField1(JPasswordField SenhajPasswordField1) {
        this.SenhajPasswordField1 = SenhajPasswordField1;
    }
    
    
   
    
}
