/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author brunocesar
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MesjButton1 = new javax.swing.JButton();
        DataIniciojFormattedTextField1 = new javax.swing.JFormattedTextField();
        DataFimjFormattedTextField2 = new javax.swing.JFormattedTextField();
        GerarjButton5 = new javax.swing.JButton();
        TresMesesjButton2 = new javax.swing.JButton();
        SeisMesesjButton3 = new javax.swing.JButton();
        AnojButton4 = new javax.swing.JButton();
        SemanajButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FundojLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatórios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Relatório por intervalo de escolha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Relatórios prontos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Data fim:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Data ínicio:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        MesjButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MesjButton1.setText("Último mês");
        getContentPane().add(MesjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 130, -1));

        try {
            DataIniciojFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(DataIniciojFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 170, 30));

        try {
            DataFimjFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(DataFimjFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 170, 30));

        GerarjButton5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        GerarjButton5.setText("Gerar Relatório");
        getContentPane().add(GerarjButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 170, -1));

        TresMesesjButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        TresMesesjButton2.setText("Últimos 3 meses");
        getContentPane().add(TresMesesjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 130, -1));

        SeisMesesjButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        SeisMesesjButton3.setText("Últimos 6 meses");
        getContentPane().add(SeisMesesjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 130, -1));

        AnojButton4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        AnojButton4.setText("Último ano");
        getContentPane().add(AnojButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 130, -1));

        SemanajButton5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        SemanajButton5.setText("Última semana");
        getContentPane().add(SemanajButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 130, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        FundojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Relatório.png"))); // NOI18N
        FundojLabel1.setText("Data ínicio:");
        getContentPane().add(FundojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 1353, 716));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnojButton4;
    private javax.swing.JFormattedTextField DataFimjFormattedTextField2;
    private javax.swing.JFormattedTextField DataIniciojFormattedTextField1;
    private javax.swing.JLabel FundojLabel1;
    private javax.swing.JButton GerarjButton5;
    private javax.swing.JButton MesjButton1;
    private javax.swing.JButton SeisMesesjButton3;
    private javax.swing.JButton SemanajButton5;
    private javax.swing.JButton TresMesesjButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
